apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-api-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flight-api

  template:
    metadata:
      labels:
        app: flight-api

    spec:
      containers:
      - name: flight-api-container
        image: flight-price:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000