apiVersion: v1
kind: Service
metadata:
  name: flight-api-service

spec:
  type: NodePort

  selector:
    app: flight-api

  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007